#' Electronic Health Record (EHR) Data Processing and Analysis Tool
#'
#' Process and analyze Electronic Health Record (EHR) Data. Implement
#' three statistical methods for Phenome Wide Association Study (PheWAS).
#'
#' Contingency tables for many binary outcomes (e.g., phenotypes) and 
#' a binary covariate (e.g., exposure) can be efficiently generated by 
#' \code{\link{zeroOneTable}}, and three commonly used statistical methods 
#' to analyze data for PheWAS can be implement by \code{\link{analysisPheWAS}}.
#'
#' @docType package
#'
#' @importFrom utils head
#' @importFrom logistf logistf.control logistpl.control
#' @import stats
#' @import data.table
#'
#' @author Leena Choi \email{naturechoi@@gmail.com},
#' Cole Beck \email{cole.beck@@vumc.org},
#' Hannah Weeks \email{hannah.l.weeks@@vanderbilt.edu}, and
#' Elizabeth McNeer \email{elizabeth.mcneer@@vumc.org}
#'
#' Maintainer: Leena Choi \email{naturechoi@gmail.com}
#' @keywords EHR process PheWAS
#' @examples
#' data(dataPheWAS)
#' demo.covariates <- c('id','exposure','age','race','gender')
#' phenotypeList <- setdiff(colnames(dd), demo.covariates)
#' tablePhenotype <- matrix(NA, ncol=4, nrow=length(phenotypeList), 
#' dimnames=list(phenotypeList, c("n.nocase.nonexp", "n.case.nonexp", 
#' "n.nocase.exp", "n.case.exp")))
#' for(i in seq_along(phenotypeList)) {
#'     tablePhenotype[i, ] <- zeroOneTable(dd[, 'exposure'], dd[, phenotypeList[i]])
#' }
#' 
#' ## use small datasets to run this example
#' data(dataPheWASsmall)
#' ## make dd.base with subset of covariates from baseline data (dd.baseline.small)
#' ## or select covariates with upper code as shown below
#' upper.code.list <- unique(sub("[.][^.]*(.).*", "", colnames(dd.baseline.small)) )
#' upper.code.list <- intersect(upper.code.list, colnames(dd.baseline.small))
#' dd.base <- dd.baseline.small[, upper.code.list]
#' ## perfrom regularized logistic regression to obtain propensity score (PS) 
#' ## to adjust for potential confounders at baseline
#' phenos <- setdiff(colnames(dd.base), c('id', 'exposure'))
#' data.x <- as.matrix(dd.base[, phenos])
#' glmnet.fit <- glmnet::cv.glmnet(x=data.x, y=dd.base[,'exposure'],
#'                                 family="binomial", standardize=TRUE,
#'                                 alpha=0.1)
#' dd.base$PS <- c(predict(glmnet.fit, data.x, s='lambda.min'))
#' data.ps <- dd.base[,c('id', 'PS')]
#' dd.all.ps <- merge(data.ps, dd.small, by='id')  
#' demographics <- c('age', 'race', 'gender')
#' phenotypeList <- setdiff(colnames(dd.small), c('id','exposure','age','race','gender'))
#' ## run with a subset of phenotypeList to get quicker results
#' phenotypeList.sub <- sample(phenotypeList, 10)
#' results.sub <- analysisPheWAS(method='firth', adjust='PS', Exposure='exposure',
#'                                                 PS='PS', demographics=demographics, 
#'                                                 phenotypes=phenotypeList.sub, data=dd.all.ps)
#' ## run with the full list of phenotype outcomes (i.e., phenotypeList)
#' \donttest{
#'         results <- analysisPheWAS(method='firth', adjust='PS',Exposure='exposure',
#'                           PS='PS', demographics=demographics,
#'                           phenotypes=phenotypeList, data=dd.all.ps) 
#' }
"_PACKAGE"

.onLoad <- function(libname, pkgname) {
  myopts <- list(
    ehr.dist_method = 'minEntEnd',
    ehr.na_penalty = 32,
    ehr.neg_penalty = 0.5,
    ehr.greedy_threshold = 1e8
  )
  options(myopts)
  invisible()
}
